drop table if exists entries;
create table datos (
  id integer primary key autoincrement,
  indicador text not null,
  region text not null,
  anio integer not null,
  dato integer
);


insert into datos (indicador, region, anio, dato) values ("PIBR", "Tarapacá", 1970, 6785);
insert into datos (indicador, region, anio, dato) values ("PIBR", "Tarapacá", 1971, 7458);
insert into datos (indicador, region, anio, dato) values ("PIBR", "Tarapacá", 1972, 7558);
insert into datos (indicador, region, anio, dato) values ("PIBR", "Tarapacá", 1973, 7385);
insert into datos (indicador, region, anio, dato) values ("PIBR", "Tarapacá", 1974, 7766);
insert into datos (indicador, region, anio, dato) values ("PIBR", "Tarapacá", 1975, 7151);
insert into datos (indicador, region, anio, dato) values ("PIBR", "Tarapacá", 1976, 7151);
insert into datos (indicador, region, anio, dato) values ("PIBR", "Tarapacá", 1977, 7567);
insert into datos (indicador, region, anio, dato) values ("PIBR", "Tarapacá", 1978, 9241);
insert into datos (indicador, region, anio, dato) values ("PIBR", "Tarapacá", 1979, 9912);
insert into datos (indicador, region, anio, dato) values ("PIBR", "Tarapacá", 1980, 11395);
insert into datos (indicador, region, anio, dato) values ("PIBR", "Tarapacá", 1981, 11351);
insert into datos (indicador, region, anio, dato) values ("PIBR", "Tarapacá", 1982, 10453);
insert into datos (indicador, region, anio, dato) values ("PIBR", "Tarapacá", 1983, 10302);
insert into datos (indicador, region, anio, dato) values ("PIBR", "Tarapacá", 1984, 11027);
insert into datos (indicador, region, anio, dato) values ("PIBR", "Tarapacá", 1985, 11850);
insert into datos (indicador, region, anio, dato) values ("PIBR", "Antofagasta", 1970, 11547);
insert into datos (indicador, region, anio, dato) values ("PIBR", "Antofagasta", 1971, 13238);
insert into datos (indicador, region, anio, dato) values ("PIBR", "Antofagasta", 1972, 11930);
insert into datos (indicador, region, anio, dato) values ("PIBR", "Antofagasta", 1973, 12321);
insert into datos (indicador, region, anio, dato) values ("PIBR", "Antofagasta", 1974, 13872);
insert into datos (indicador, region, anio, dato) values ("PIBR", "Antofagasta", 1975, 12177);
insert into datos (indicador, region, anio, dato) values ("PIBR", "Antofagasta", 1976, 14789);
insert into datos (indicador, region, anio, dato) values ("PIBR", "Antofagasta", 1977, 16091);
insert into datos (indicador, region, anio, dato) values ("PIBR", "Antofagasta", 1978, 18063);
insert into datos (indicador, region, anio, dato) values ("PIBR", "Antofagasta", 1979, 18400);
insert into datos (indicador, region, anio, dato) values ("PIBR", "Antofagasta", 1980, 19657);
insert into datos (indicador, region, anio, dato) values ("PIBR", "Antofagasta", 1981, 19401);
insert into datos (indicador, region, anio, dato) values ("PIBR", "Antofagasta", 1982, 20425);
insert into datos (indicador, region, anio, dato) values ("PIBR", "Antofagasta", 1983, 20081);
insert into datos (indicador, region, anio, dato) values ("PIBR", "Antofagasta", 1984, 20687);
insert into datos (indicador, region, anio, dato) values ("PIBR", "Antofagasta", 1985, 20446);
insert into datos (indicador, region, anio, dato) values ("PIBR", "Atacama", 1970, 5145);
insert into datos (indicador, region, anio, dato) values ("PIBR", "Atacama", 1971, 4846);
insert into datos (indicador, region, anio, dato) values ("PIBR", "Atacama", 1972, 4368);
insert into datos (indicador, region, anio, dato) values ("PIBR", "Atacama", 1973, 4130);
insert into datos (indicador, region, anio, dato) values ("PIBR", "Atacama", 1974, 4781);
insert into datos (indicador, region, anio, dato) values ("PIBR", "Atacama", 1975, 4694);
insert into datos (indicador, region, anio, dato) values ("PIBR", "Atacama", 1976, 4705);
insert into datos (indicador, region, anio, dato) values ("PIBR", "Atacama", 1977, 4613);
insert into datos (indicador, region, anio, dato) values ("PIBR", "Atacama", 1978, 5296);
insert into datos (indicador, region, anio, dato) values ("PIBR", "Atacama", 1979, 5947);
insert into datos (indicador, region, anio, dato) values ("PIBR", "Atacama", 1980, 6788);
insert into datos (indicador, region, anio, dato) values ("PIBR", "Atacama", 1981, 7386);
insert into datos (indicador, region, anio, dato) values ("PIBR", "Atacama", 1982, 6705);
insert into datos (indicador, region, anio, dato) values ("PIBR", "Atacama", 1983, 6856);
insert into datos (indicador, region, anio, dato) values ("PIBR", "Atacama", 1984, 7315);
insert into datos (indicador, region, anio, dato) values ("PIBR", "Atacama", 1985, 7990);
insert into datos (indicador, region, anio, dato) values ("PIBR", "Coquimbo", 1970, 4329);
insert into datos (indicador, region, anio, dato) values ("PIBR", "Coquimbo", 1971, 4640);
insert into datos (indicador, region, anio, dato) values ("PIBR", "Coquimbo", 1972, 4656);
insert into datos (indicador, region, anio, dato) values ("PIBR", "Coquimbo", 1973, 4840);
insert into datos (indicador, region, anio, dato) values ("PIBR", "Coquimbo", 1974, 5027);
insert into datos (indicador, region, anio, dato) values ("PIBR", "Coquimbo", 1975, 4947);
insert into datos (indicador, region, anio, dato) values ("PIBR", "Coquimbo", 1976, 5166);
insert into datos (indicador, region, anio, dato) values ("PIBR", "Coquimbo", 1977, 5440);
insert into datos (indicador, region, anio, dato) values ("PIBR", "Coquimbo", 1978, 5827);
insert into datos (indicador, region, anio, dato) values ("PIBR", "Coquimbo", 1979, 6394);
insert into datos (indicador, region, anio, dato) values ("PIBR", "Coquimbo", 1980, 6880);
insert into datos (indicador, region, anio, dato) values ("PIBR", "Coquimbo", 1981, 6979);
insert into datos (indicador, region, anio, dato) values ("PIBR", "Coquimbo", 1982, 6713);
insert into datos (indicador, region, anio, dato) values ("PIBR", "Coquimbo", 1983, 6843);
insert into datos (indicador, region, anio, dato) values ("PIBR", "Coquimbo", 1984, 7400);
insert into datos (indicador, region, anio, dato) values ("PIBR", "Coquimbo", 1985, 7696);
insert into datos (indicador, region, anio, dato) values ("PIBR", "Valparaíso", 1970, 29909);
insert into datos (indicador, region, anio, dato) values ("PIBR", "Valparaíso", 1971, 33418);
insert into datos (indicador, region, anio, dato) values ("PIBR", "Valparaíso", 1972, 32698);
insert into datos (indicador, region, anio, dato) values ("PIBR", "Valparaíso", 1973, 31712);
insert into datos (indicador, region, anio, dato) values ("PIBR", "Valparaíso", 1974, 35147);
insert into datos (indicador, region, anio, dato) values ("PIBR", "Valparaíso", 1975, 30421);
insert into datos (indicador, region, anio, dato) values ("PIBR", "Valparaíso", 1976, 31650);
insert into datos (indicador, region, anio, dato) values ("PIBR", "Valparaíso", 1977, 33720);
insert into datos (indicador, region, anio, dato) values ("PIBR", "Valparaíso", 1978, 34752);
insert into datos (indicador, region, anio, dato) values ("PIBR", "Valparaíso", 1979, 36626);
insert into datos (indicador, region, anio, dato) values ("PIBR", "Valparaíso", 1980, 37370);
insert into datos (indicador, region, anio, dato) values ("PIBR", "Valparaíso", 1981, 38052);
insert into datos (indicador, region, anio, dato) values ("PIBR", "Valparaíso", 1982, 32678);
insert into datos (indicador, region, anio, dato) values ("PIBR", "Valparaíso", 1983, 33217);
insert into datos (indicador, region, anio, dato) values ("PIBR", "Valparaíso", 1984, 35148);
insert into datos (indicador, region, anio, dato) values ("PIBR", "Valparaíso", 1985, 35890);
insert into datos (indicador, region, anio, dato) values ("PIBR", "OHiggins", 1970, 14467);
insert into datos (indicador, region, anio, dato) values ("PIBR", "OHiggins", 1971, 14093);
insert into datos (indicador, region, anio, dato) values ("PIBR", "OHiggins", 1972, 14857);
insert into datos (indicador, region, anio, dato) values ("PIBR", "OHiggins", 1973, 13838);
insert into datos (indicador, region, anio, dato) values ("PIBR", "OHiggins", 1974, 17001);
insert into datos (indicador, region, anio, dato) values ("PIBR", "OHiggins", 1975, 15478);
insert into datos (indicador, region, anio, dato) values ("PIBR", "OHiggins", 1976, 14952);
insert into datos (indicador, region, anio, dato) values ("PIBR", "OHiggins", 1977, 16043);
insert into datos (indicador, region, anio, dato) values ("PIBR", "OHiggins", 1978, 16587);
insert into datos (indicador, region, anio, dato) values ("PIBR", "OHiggins", 1979, 18395);
insert into datos (indicador, region, anio, dato) values ("PIBR", "OHiggins", 1980, 19011);
insert into datos (indicador, region, anio, dato) values ("PIBR", "OHiggins", 1981, 20033);
insert into datos (indicador, region, anio, dato) values ("PIBR", "OHiggins", 1982, 20584);
insert into datos (indicador, region, anio, dato) values ("PIBR", "OHiggins", 1983, 18887);
insert into datos (indicador, region, anio, dato) values ("PIBR", "OHiggins", 1984, 19756);
insert into datos (indicador, region, anio, dato) values ("PIBR", "OHiggins", 1985, 21246);
insert into datos (indicador, region, anio, dato) values ("PIBR", "Maule", 1970, 9716);
insert into datos (indicador, region, anio, dato) values ("PIBR", "Maule", 1971, 9799);
insert into datos (indicador, region, anio, dato) values ("PIBR", "Maule", 1972, 9639);
insert into datos (indicador, region, anio, dato) values ("PIBR", "Maule", 1973, 8568);
insert into datos (indicador, region, anio, dato) values ("PIBR", "Maule", 1974, 9406);
insert into datos (indicador, region, anio, dato) values ("PIBR", "Maule", 1975, 9871);
insert into datos (indicador, region, anio, dato) values ("PIBR", "Maule", 1976, 10194);
insert into datos (indicador, region, anio, dato) values ("PIBR", "Maule", 1977, 11194);
insert into datos (indicador, region, anio, dato) values ("PIBR", "Maule", 1978, 11172);
insert into datos (indicador, region, anio, dato) values ("PIBR", "Maule", 1979, 11903);
insert into datos (indicador, region, anio, dato) values ("PIBR", "Maule", 1980, 11815);
insert into datos (indicador, region, anio, dato) values ("PIBR", "Maule", 1981, 12676);
insert into datos (indicador, region, anio, dato) values ("PIBR", "Maule", 1982, 12926);
insert into datos (indicador, region, anio, dato) values ("PIBR", "Maule", 1983, 12995);
insert into datos (indicador, region, anio, dato) values ("PIBR", "Maule", 1984, 13536);
insert into datos (indicador, region, anio, dato) values ("PIBR", "Maule", 1985, 14350);
insert into datos (indicador, region, anio, dato) values ("PIBR", "Biobío", 1970, 25128);
insert into datos (indicador, region, anio, dato) values ("PIBR", "Biobío", 1971, 28767);
insert into datos (indicador, region, anio, dato) values ("PIBR", "Biobío", 1972, 28314);
insert into datos (indicador, region, anio, dato) values ("PIBR", "Biobío", 1973, 26920);
insert into datos (indicador, region, anio, dato) values ("PIBR", "Biobío", 1974, 27656);
insert into datos (indicador, region, anio, dato) values ("PIBR", "Biobío", 1975, 24124);
insert into datos (indicador, region, anio, dato) values ("PIBR", "Biobío", 1976, 26256);
insert into datos (indicador, region, anio, dato) values ("PIBR", "Biobío", 1977, 27930);
insert into datos (indicador, region, anio, dato) values ("PIBR", "Biobío", 1978, 28099);
insert into datos (indicador, region, anio, dato) values ("PIBR", "Biobío", 1979, 29977);
insert into datos (indicador, region, anio, dato) values ("PIBR", "Biobío", 1980, 33960);
insert into datos (indicador, region, anio, dato) values ("PIBR", "Biobío", 1981, 34437);
insert into datos (indicador, region, anio, dato) values ("PIBR", "Biobío", 1982, 29743);
insert into datos (indicador, region, anio, dato) values ("PIBR", "Biobío", 1983, 31869);
insert into datos (indicador, region, anio, dato) values ("PIBR", "Biobío", 1984, 34438);
insert into datos (indicador, region, anio, dato) values ("PIBR", "Biobío", 1985, 35742);
insert into datos (indicador, region, anio, dato) values ("PIBR", "Araucanía", 1970, 8194);
insert into datos (indicador, region, anio, dato) values ("PIBR", "Araucanía", 1971, 9014);
insert into datos (indicador, region, anio, dato) values ("PIBR", "Araucanía", 1972, 9001);
insert into datos (indicador, region, anio, dato) values ("PIBR", "Araucanía", 1973, 8223);
insert into datos (indicador, region, anio, dato) values ("PIBR", "Araucanía", 1974, 8974);
insert into datos (indicador, region, anio, dato) values ("PIBR", "Araucanía", 1975, 8866);
insert into datos (indicador, region, anio, dato) values ("PIBR", "Araucanía", 1976, 9012);
insert into datos (indicador, region, anio, dato) values ("PIBR", "Araucanía", 1977, 9745);
insert into datos (indicador, region, anio, dato) values ("PIBR", "Araucanía", 1978, 9572);
insert into datos (indicador, region, anio, dato) values ("PIBR", "Araucanía", 1979, 10028);
insert into datos (indicador, region, anio, dato) values ("PIBR", "Araucanía", 1980, 10852);
insert into datos (indicador, region, anio, dato) values ("PIBR", "Araucanía", 1981, 10900);
insert into datos (indicador, region, anio, dato) values ("PIBR", "Araucanía", 1982, 9879);
insert into datos (indicador, region, anio, dato) values ("PIBR", "Araucanía", 1983, 10347);
insert into datos (indicador, region, anio, dato) values ("PIBR", "Araucanía", 1984, 11056);
insert into datos (indicador, region, anio, dato) values ("PIBR", "Araucanía", 1985, 11576);
insert into datos (indicador, region, anio, dato) values ("PIBR", "Los Lagos", 1970, 12271);
insert into datos (indicador, region, anio, dato) values ("PIBR", "Los Lagos", 1971, 13312);
insert into datos (indicador, region, anio, dato) values ("PIBR", "Los Lagos", 1972, 13023);
insert into datos (indicador, region, anio, dato) values ("PIBR", "Los Lagos", 1973, 12640);
insert into datos (indicador, region, anio, dato) values ("PIBR", "Los Lagos", 1974, 13467);
insert into datos (indicador, region, anio, dato) values ("PIBR", "Los Lagos", 1975, 13015);
insert into datos (indicador, region, anio, dato) values ("PIBR", "Los Lagos", 1976, 13332);
insert into datos (indicador, region, anio, dato) values ("PIBR", "Los Lagos", 1977, 13904);
insert into datos (indicador, region, anio, dato) values ("PIBR", "Los Lagos", 1978, 14157);
insert into datos (indicador, region, anio, dato) values ("PIBR", "Los Lagos", 1979, 14327);
insert into datos (indicador, region, anio, dato) values ("PIBR", "Los Lagos", 1980, 15667);
insert into datos (indicador, region, anio, dato) values ("PIBR", "Los Lagos", 1981, 16121);
insert into datos (indicador, region, anio, dato) values ("PIBR", "Los Lagos", 1982, 14802);
insert into datos (indicador, region, anio, dato) values ("PIBR", "Los Lagos", 1983, 14980);
insert into datos (indicador, region, anio, dato) values ("PIBR", "Los Lagos", 1984, 15768);
insert into datos (indicador, region, anio, dato) values ("PIBR", "Los Lagos", 1985, 16642);
insert into datos (indicador, region, anio, dato) values ("PIBR", "Aysén", 1970, 1230);
insert into datos (indicador, region, anio, dato) values ("PIBR", "Aysén", 1971, 1269);
insert into datos (indicador, region, anio, dato) values ("PIBR", "Aysén", 1972, 1247);
insert into datos (indicador, region, anio, dato) values ("PIBR", "Aysén", 1973, 1293);
insert into datos (indicador, region, anio, dato) values ("PIBR", "Aysén", 1974, 1178);
insert into datos (indicador, region, anio, dato) values ("PIBR", "Aysén", 1975, 1162);
insert into datos (indicador, region, anio, dato) values ("PIBR", "Aysén", 1976, 1182);
insert into datos (indicador, region, anio, dato) values ("PIBR", "Aysén", 1977, 1297);
insert into datos (indicador, region, anio, dato) values ("PIBR", "Aysén", 1978, 1357);
insert into datos (indicador, region, anio, dato) values ("PIBR", "Aysén", 1979, 1463);
insert into datos (indicador, region, anio, dato) values ("PIBR", "Aysén", 1980, 1488);
insert into datos (indicador, region, anio, dato) values ("PIBR", "Aysén", 1981, 1455);
insert into datos (indicador, region, anio, dato) values ("PIBR", "Aysén", 1982, 1506);
insert into datos (indicador, region, anio, dato) values ("PIBR", "Aysén", 1983, 1545);
insert into datos (indicador, region, anio, dato) values ("PIBR", "Aysén", 1984, 1572);
insert into datos (indicador, region, anio, dato) values ("PIBR", "Aysén", 1985, 1654);
insert into datos (indicador, region, anio, dato) values ("PIBR", "Magallanes", 1970, 7254);
insert into datos (indicador, region, anio, dato) values ("PIBR", "Magallanes", 1971, 8157);
insert into datos (indicador, region, anio, dato) values ("PIBR", "Magallanes", 1972, 7691);
insert into datos (indicador, region, anio, dato) values ("PIBR", "Magallanes", 1973, 6992);
insert into datos (indicador, region, anio, dato) values ("PIBR", "Magallanes", 1974, 7447);
insert into datos (indicador, region, anio, dato) values ("PIBR", "Magallanes", 1975, 6229);
insert into datos (indicador, region, anio, dato) values ("PIBR", "Magallanes", 1976, 6355);
insert into datos (indicador, region, anio, dato) values ("PIBR", "Magallanes", 1977, 6723);
insert into datos (indicador, region, anio, dato) values ("PIBR", "Magallanes", 1978, 7672);
insert into datos (indicador, region, anio, dato) values ("PIBR", "Magallanes", 1979, 7907);
insert into datos (indicador, region, anio, dato) values ("PIBR", "Magallanes", 1980, 9676);
insert into datos (indicador, region, anio, dato) values ("PIBR", "Magallanes", 1981, 10520);
insert into datos (indicador, region, anio, dato) values ("PIBR", "Magallanes", 1982, 9807);
insert into datos (indicador, region, anio, dato) values ("PIBR", "Magallanes", 1983, 10046);
insert into datos (indicador, region, anio, dato) values ("PIBR", "Magallanes", 1984, 10389);
insert into datos (indicador, region, anio, dato) values ("PIBR", "Magallanes", 1985, 10188);
insert into datos (indicador, region, anio, dato) values ("PIBR", "Metropolitana", 1970, 131658);
insert into datos (indicador, region, anio, dato) values ("PIBR", "Metropolitana", 1971, 144589);
insert into datos (indicador, region, anio, dato) values ("PIBR", "Metropolitana", 1972, 144320);
insert into datos (indicador, region, anio, dato) values ("PIBR", "Metropolitana", 1973, 134565);
insert into datos (indicador, region, anio, dato) values ("PIBR", "Metropolitana", 1974, 127654);
insert into datos (indicador, region, anio, dato) values ("PIBR", "Metropolitana", 1975, 106789);
insert into datos (indicador, region, anio, dato) values ("PIBR", "Metropolitana", 1976, 108548);
insert into datos (indicador, region, anio, dato) values ("PIBR", "Metropolitana", 1977, 119512);
insert into datos (indicador, region, anio, dato) values ("PIBR", "Metropolitana", 1978, 133242);
insert into datos (indicador, region, anio, dato) values ("PIBR", "Metropolitana", 1979, 146451);
insert into datos (indicador, region, anio, dato) values ("PIBR", "Metropolitana", 1980, 155039);
insert into datos (indicador, region, anio, dato) values ("PIBR", "Metropolitana", 1981, 162282);
insert into datos (indicador, region, anio, dato) values ("PIBR", "Metropolitana", 1982, 135474);
insert into datos (indicador, region, anio, dato) values ("PIBR", "Metropolitana", 1983, 134487);
insert into datos (indicador, region, anio, dato) values ("PIBR", "Metropolitana", 1984, 142037);
insert into datos (indicador, region, anio, dato) values ("PIBR", "Metropolitana", 1985, 145270);
insert into datos (indicador, region, anio, dato) values ("PIBR", "S/R", 1970, 15463);
insert into datos (indicador, region, anio, dato) values ("PIBR", "S/R", 1971, 15850);
insert into datos (indicador, region, anio, dato) values ("PIBR", "S/R", 1972, 15405);
insert into datos (indicador, region, anio, dato) values ("PIBR", "S/R", 1973, 14322);
insert into datos (indicador, region, anio, dato) values ("PIBR", "S/R", 1974, 11177);
insert into datos (indicador, region, anio, dato) values ("PIBR", "S/R", 1975, 8119);
insert into datos (indicador, region, anio, dato) values ("PIBR", "S/R", 1976, 8645);
insert into datos (indicador, region, anio, dato) values ("PIBR", "S/R", 1977, 13990);
insert into datos (indicador, region, anio, dato) values ("PIBR", "S/R", 1978, 16351);
insert into datos (indicador, region, anio, dato) values ("PIBR", "S/R", 1979, 19478);
insert into datos (indicador, region, anio, dato) values ("PIBR", "S/R", 1980, 23850);
insert into datos (indicador, region, anio, dato) values ("PIBR", "S/R", 1981, 31959);
insert into datos (indicador, region, anio, dato) values ("PIBR", "S/R", 1982, 17829);
insert into datos (indicador, region, anio, dato) values ("PIBR", "S/R", 1983, 14725);
insert into datos (indicador, region, anio, dato) values ("PIBR", "S/R", 1984, 17797);
insert into datos (indicador, region, anio, dato) values ("PIBR", "S/R", 1985, 15907);

